=== SamyakOe/rakriti/XML/q13/hospital.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Hospital">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="patient" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="pname">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="firstname" type="xs:string" />
                                        <xs:element name="middlename" type="xs:string" />
                                        <xs:element name="lastname" type="xs:string" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="patientnumber">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:length value="5" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="DoctorName" type="xs:string" />
                            <xs:element name="Diseases">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="Disease" type="xs:string"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="consultationcharge">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="500" />
                                        <xs:maxInclusive value="5000" />
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="LabTests">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="test" type="xs:string"
                                            maxOccurs="unbounded" />
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== SamyakOe/rakriti/XML/q13/hospital.xml
<?xml version="1.0" encoding="UTF-8"?>
<Hospital xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="hospital.xsd">
    <patient>
        <pname>
            <firstname>Sarita</firstname>
            <middlename>Kumari</middlename>
            <lastname>Thapa</lastname>
        </pname>
        <patientnumber>15425</patientnumber>
        <DoctorName>Dr. Hari Kunwar</DoctorName>
        <Diseases>
            <Disease>Influenza</Disease>
            <Disease>Pneumonia</Disease>
        </Diseases>
        <consultationcharge>1500</consultationcharge>
        <LabTests>
            <test>Blood Test</test>
            <test>Urine Test</test>
        </LabTests>
    </patient>
</Hospital>
